Vagrant.configure("2") do |config|

  config.vm.define "project-docker-host", primary: true do |dhost|

    dhost.vm.box = "ailispaw/rancheros-lite"
    dhost.vm.network :private_network, ip: "192.168.100.250"
    dhost.vm.provider "virtualbox" do |v|

      v.name = "project-docker-host"
      v.memory = 2048

    end

  end

end
